# Generated by Django 4.2.10 on 2024-02-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('document_type', models.CharField(max_length=20, verbose_name='Tipo de Documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Numero de Documento')),
                ('birthdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numero de Telefono')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('martial_status', models.CharField(max_length=20, verbose_name='Estado Civil')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('job', models.CharField(max_length=50, verbose_name='Cargo')),
                ('department', models.CharField(max_length=50, verbose_name='Departamento')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('date_hired', models.DateField(auto_now_add=True, verbose_name='Fecha de Contratación')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'employee',
            },
        ),
    ]
